name: "Deploy FoodBuddy"

on:
  push:

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 3.1.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Publish
        run: dotnet publish FoodBuddy.csproj -c Release -o release -r win-x64 -p:PublishSingleFile=true
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: FoodBuddy_Artifact
          path: release

      - name: Release
        uses: csexton/release-asset-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: /bin/Release/net6.0-windows/win-x64/publish/*.exe
          release-url: ${{ steps.create_release.outputs.upload_url }}
          

        

